# Generated by Django 5.1.3 on 2024-11-10 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=250)),
                ("json_field", models.JSONField(blank=True, null=True)),
                ("is_block", models.BooleanField(default=False)),
                ("is_temp_block", models.BooleanField(default=False)),
                ("is_challenge", models.BooleanField(default=False)),
                ("number_of_use", models.IntegerField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("last_use_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_posts", models.JSONField(blank=True, null=True)),
                ("profile", models.CharField(blank=True, max_length=250, null=True)),
                ("loading_time", models.CharField(max_length=250)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instagram_crawler.session",
                    ),
                ),
            ],
        ),
    ]
