# Generated by Django 5.1.3 on 2024-11-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_crawler", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="json_field",
            new_name="session_data",
        ),
    ]
