# Generated by Django 5.1.3 on 2024-11-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_crawler", "0002_rename_json_field_session_session_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="json_posts",
            new_name="post_data",
        ),
    ]
