# Generated by Django 5.1.3 on 2024-11-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_crawler", "0003_rename_json_posts_post_post_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("spot", models.CharField(max_length=250)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
