# Generated by Django 5.1.3 on 2024-11-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_crawler", "0004_error"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Error",
            new_name="log",
        ),
    ]
