# Generated by Django 5.1.3 on 2024-12-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_crawler", "0006_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="code",
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
